backend:
  image:
    repository: ghcr.io/yfk1m/tms/backend
    tag: "v0.0.5"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  secretName: tms-secrets

frontend:
  image:
    repository: ghcr.io/yfk1m/tms/frontend
    tag: "v0.0.2"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 80

postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
  port: 5432
  secretName: tms-secrets
  storage:
    size: 5Gi
    storageClassName: longhorn

httpRoute:
  enabled: true
  frontend:
    hostname: tms.ywa.red
  backend:
    hostname: back.tms.ywa.red
  gateway:
    name: main
    namespace: gateway
